### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by pengbeilin** [huzenan/EasyTransition#1]
求教博主，那个我用了博主的两个工具类，在activity场景切换的时候，文字变动起来扭曲了，不是那种大小缩放，求教是什么地方出了问题

**Comment by huzenan** [comment]
扭曲是啥意思，有代码贴上来看一下不，或者直接QQ联系看看是什么情况。

**Comment by huzenan** [comment]
转场时计算的是控件本身的宽高，例如TextView的宽度设置为 match_parent 的话宽度就不一定是文字本身的宽度了，所以会有你说的扭曲的感觉。
