### ISSUE TITLE
请问你这个能兼容5.0以下系统吗？

### ISSUE THREAD

**Issue by coolstar1204** [huzenan/EasyTransition#4]
再请问一下，你这个能用到fragment到fragment的共享元素动画吗？
我找了很久，发现都是activity到activity的共享元素切换动画，或fragment到activity的共享元素动画，
就没有fragment到fragment的。我测试发现，fragment到fragment的共享元素动画，好像只能应用到
replace方式，好像fragment如果是add进来的，不能工作。

**Comment by huzenan** [comment]
你好，可以兼容3.0及以上的系统，因为使用的是属性动画；
另外，EasyTransition目前不支持Fragment的，后面有空会考虑加上该功能，谢谢！

**Comment by liya7907** [comment]
您好 不支持Fragment跳Activity的是吧，能不能提供个思路我基于您的代码修改下，目前想用您这个库来实现一个视频播放器全屏播放到视频详情页的视频播放区的一个共享元素动画，按demo尝试后没有效果。能提供个思路么？感谢。
